/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;


public class AddStocksFrame extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    Statement stmt;
  
    public String hsn_code, item_name, tax_slab;
    
    
    public AddStocksFrame() {

        initComponents();
        try{
//            this.setExtendedState(AddStocksFrame.MAXIMIZED_BOTH);
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/BILLING","root","root");
            stmt = con.createStatement();
            txtcode.setVisible(false);
            /*
            if(hsn_code != null)
            {
                String s = "SELECT * FROM STOCKS WHERE HSN_CODE = '"+hsn_code+"'";
                rs = stmt.executeQuery(s);
                rs.first();
                
                txtHSN.setText(rs.getString("HSN_CODE"));
                txtItem.setText(rs.getString("ITEM_NAME"));
                tax_slab = rs.getString("TAX_SLAB");
                
                switch(tax_slab){
                
                    case "0":
                        cmbTax.setSelectedIndex(0);
                        break;
                    case "5":
                        cmbTax.setSelectedIndex(1);
                        break;
                    case "12":
                        cmbTax.setSelectedIndex(2);
                        break;
                    case "18":
                        cmbTax.setSelectedIndex(3);
                        break;      
                }
            }
            */
            
           }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public AddStocksFrame(String hsn_codes) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.hsn_code = hsn_codes;
        initComponents();
        populateData();
    }
    
    public void populateData()
    {
        
        try
        {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/BILLING","root","root");
                stmt = con.createStatement();
                txtcode.setVisible(false);
                String s = "SELECT * FROM STOCKS WHERE HSN_CODE = '"+hsn_code+"'";
                rs = stmt.executeQuery(s);
                rs.first();
                
                txtHSN.setText(rs.getString("HSN_CODE"));
                txtItem.setText(rs.getString("ITEM_NAME"));
                tax_slab = rs.getString("TAX_SLAB");
                txtcode.setText(rs.getString("ITEM_NO"));
                switch(tax_slab){
                
                    case "0":
                        cmbTax.setSelectedIndex(0);
                        break;
                    case "5":
                        cmbTax.setSelectedIndex(1);
                        break;
                    case "12":
                        cmbTax.setSelectedIndex(2);
                        break;
                    case "18":
                        cmbTax.setSelectedIndex(3);
                        break;      
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnLoad = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnViewStock = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHSN = new javax.swing.JTextField();
        txtItem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbTax = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lblClick = new javax.swing.JLabel();
        lblPath = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        txtcode = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ADD STOCK");
        jLabel1.setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setAutoscrolls(true);

        btnPrevious.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrevious.setText("<PREVIOUS");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setText("NEXT>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnPrevious)
                .addGap(27, 27, 27)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setAutoscrolls(true);

        btnLoad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLoad.setText("LOAD");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setAutoscrolls(true);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewStock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewStock.setText("VIEW STOCK>>");
        btnViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStockActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnViewStock)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewStock, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("HSN Code:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Item Name:");

        txtHSN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtHSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHSNKeyTyped(evt);
            }
        });

        txtItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Tax Slab:");

        cmbTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbTax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "5%", "12%", "18%" }));
        cmbTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTaxActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Choose a CSV File to update Stocks");

        lblClick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClick.setForeground(new java.awt.Color(255, 0, 0));
        lblClick.setText("CLICK HERE");
        lblClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClickMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTax, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItem, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(txtHSN))
                .addGap(67, 67, 67)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblClick))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPath, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtHSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(42, 42, 42)
                .addComponent(lblClick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPath, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblError.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setAutoscrolls(true);

        btnUpload.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpload.setText("UPLOAD");
        btnUpload.setAutoscrolls(true);
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcode)
                .addGap(551, 551, 551))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(617, 617, 617))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcode))
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTaxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        AdminFrame open = new AdminFrame();
        open.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtHSN.setText("");
        txtItem.setText("");
        lblError.setText("");
        cmbTax.setSelectedIndex(0);

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
         hsn_code = txtHSN.getText().toUpperCase().trim();
         item_name = txtItem.getText().toUpperCase().trim();
        
         tax_slab = cmbTax.getSelectedItem().toString();
        String tax[] = tax_slab.split("%");
        double tax_rate = Double.parseDouble(tax[0]);
        //System.out.println(hsncode + " " + item_name + " " + tax_rate);
        
        try 
        {
            if(!(hsn_code.equals("") || item_name.equals("")))
            {
                int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to add '"+item_name+"' in the stock?");
                if(i == 0)
                {
                    String s = "INSERT INTO STOCKS (HSN_CODE, ITEM_NAME, TAX_SLAB) VALUES ('"+hsn_code+"', '"+item_name+"',"+tax_rate+")";
                    stmt.executeUpdate(s);
                    JOptionPane.showMessageDialog(null, "ITEM ADDED");
                    txtHSN.setText("");
                    txtItem.setText("");
                    cmbTax.setSelectedIndex(0);
                    lblError.setText("");
                }
                
            }
            else
            {
                lblError.setText("Please fill the required details");      
            }
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStockActionPerformed

        ViewStocksFrame open = new ViewStocksFrame();
        open.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewStockActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        
        try 
        {
            String s = "SELECT * FROM STOCKS";
            rs = stmt.executeQuery(s);
            rs.first();
            
            hsn_code = rs.getString("HSN_CODE");
            item_name = rs.getString("ITEM_NAME");
            tax_slab = rs.getString("TAX_SLAB");
            txtcode.setText(rs.getString("ITEM_NO"));
            lblError.setText("");
            txtHSN.setText(hsn_code);
            txtItem.setText(item_name);
            //System.out.println(hsn_code + item_name + tax_slab);
            switch(tax_slab){
                
                    case "0":
                        cmbTax.setSelectedIndex(0);
                        break;
                    case "5":
                        cmbTax.setSelectedIndex(1);
                        break;
                    case "12":
                        cmbTax.setSelectedIndex(2);
                        break;
                    case "18":
                        cmbTax.setSelectedIndex(3);
                        break;      
                }    
             
            
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        //String hsn_code, item_name, tax_slab;
        try 
        {
         if(!(txtItem.getText().equals("") || txtHSN.getText().equals("")))
         {
            
                if(rs.next())
                    {
                    lblError.setText("");
                    hsn_code = rs.getString("HSN_CODE");
                    item_name = rs.getString("ITEM_NAME");
                    tax_slab = rs.getString("TAX_SLAB");
                    txtcode.setText(rs.getString("ITEM_NO"));

                    txtHSN.setText(hsn_code);
                    txtItem.setText(item_name);
                    //System.out.println(hsn_code + item_name + tax_slab);
                    if("0".equals(tax_slab))
                    {
                        cmbTax.setSelectedIndex(0);
                    }
                    else if("5".equals(tax_slab))
                    {
                        cmbTax.setSelectedIndex(1);
                    }
                    else if("12".equals(tax_slab))
                    {
                        cmbTax.setSelectedIndex(2);
                    }
                    else if("18".equals(tax_slab))
                    {
                        cmbTax.setSelectedIndex(3);
                    }
                    else
                    {
                        cmbTax.setSelectedIndex(0);
                    } 
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "You're at the end of the list"); 
                }
         }
         else
         {
         lblError.setText("Please fill the details");
         }
            
           
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed

        //String hsn_code, item_name, tax_slab;
        try 
        {
           if(!(txtItem.getText().equals("") || txtHSN.getText().equals("")))
            {
                if(rs.previous())
                { 
                    lblError.setText("");
                    hsn_code = rs.getString("HSN_CODE");
                    item_name = rs.getString("ITEM_NAME");
                    tax_slab = rs.getString("TAX_SLAB");
                    txtcode.setText(rs.getString("ITEM_NO"));

                    txtHSN.setText(hsn_code);
                    txtItem.setText(item_name);
                    //System.out.println(hsn_code + item_name + tax_slab);
                    if("0".equals(tax_slab))
                    {
                        cmbTax.setSelectedIndex(0);
                    }
                    else if("5".equals(tax_slab))
                    {
                        cmbTax.setSelectedIndex(1);
                    }
                    else if("12".equals(tax_slab))
                    {
                        cmbTax.setSelectedIndex(2);
                    }
                    else if("18".equals(tax_slab))
                    {
                        cmbTax.setSelectedIndex(3);
                    }
                    else
                    {
                        cmbTax.setSelectedIndex(0);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "You're at the end of the list");
                }
            }
           else
           {
            lblError.setText("Please fill the details!");
           }
                 
             
            
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }

        
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        hsn_code = txtHSN.getText().toUpperCase().trim();
        item_name = txtItem.getText().toUpperCase().trim();
        
        
        if(!(item_name.equals("") || hsn_code.equals("")))
        {
                    int item_code = Integer.parseInt(txtcode.getText().trim());
                    tax_slab = cmbTax.getSelectedItem().toString();
                    String tax[] = tax_slab.split("%");
                    double tax_rate = Double.parseDouble(tax[0]);

                    try 
                    {
                        if(!(hsn_code.equals("")) && !(item_name.equals("")))
                        {
                        int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this '"+item_name+"' in the stock?");
                            if(i == 0)
                            {
                            String s = "UPDATE STOCKS SET HSN_CODE = '"+hsn_code+"', ITEM_NAME = '"+item_name+"', TAX_SLAB = "+tax_rate+" WHERE ITEM_NO = "+item_code+" ";
                            stmt.executeUpdate(s);
                            JOptionPane.showMessageDialog(null, "ITEM UPDATED");
                            }

                        }
                        else
                        {
                            lblError.setText("Please fill the required details");
                        }    
                    } 
                    catch (Exception e) 
                    {
                        JOptionPane.showMessageDialog(null, e);
                    }
        }
        else
        {
         lblError.setText("Please fill the details");        
        }
       
           
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        
      
        try 
        {
            if(!(txtItem.getText().equals("") || txtHSN.getText().equals("")))
            {
            int item_code = Integer.parseInt(txtcode.getText().trim());
            int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this '"+txtItem.getText()+"' from the stock?");
            if(i == 0)
            {
            String s = "DELETE FROM STOCKS WHERE ITEM_NO = "+item_code+" ";
            stmt.executeUpdate(s);
            JOptionPane.showMessageDialog(null, "ITEM DELETED");
            txtHSN.setText("");
            txtItem.setText("");
            cmbTax.setSelectedIndex(0);
            }
            }
            else
            {
               lblError.setText("Please select an Item");
            }
              
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        
        try
        {
            if(!"".equals(lblPath.getText()))
            {
                char c1 = '/';   
                char c2 = '\\';
                String d_path = lblPath.getText().trim();
                d_path = d_path.replace(c2,c1);
                
                // Setting LOAD LOCAL INFILE RULE
                stmt.executeQuery("SET GLOBAL local_infile = 1;");
                
                stmt.executeUpdate("TRUNCATE TABLE STOCKS");
                
                String qry = "LOAD DATA LOCAL INFILE '"+d_path+"' INTO TABLE STOCKS FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\\r\\n' IGNORE 1 LINES (@col1,  @col2, @col3) SET HSN_CODE = @col1, ITEM_NAME = @col2, TAX_SLAB = @col3";
                stmt.executeUpdate(qry);
       
                JOptionPane.showMessageDialog(null,"STOCKS UPDATED");
                lblPath.setText("");
            } else {
              
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void lblClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClickMouseClicked

        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); 
  
            // resctrict the user to selec files of all types 
            j.setAcceptAllFileFilterUsed(false); 
  
            // set a title for the dialog 
            j.setDialogTitle("Select a .csv file"); 
  
            // only allow files of .txt extension 
            FileNameExtensionFilter restrict = new FileNameExtensionFilter("Only .csv files", "csv"); 
            j.addChoosableFileFilter(restrict); 
  
            // invoke the showsOpenDialog function to show the save dialog 
            int r = j.showOpenDialog(null); 
  
            // if the user selects a file 
            if (r == JFileChooser.APPROVE_OPTION) { 
                // set the label to the path of the selected file 
                lblPath.setText(j.getSelectedFile().getAbsolutePath()); 
            } 
            // if the user cancelled the operation 
           
        
        
    }//GEN-LAST:event_lblClickMouseClicked

    private void txtHSNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHSNKeyTyped

       char vchar = evt.getKeyChar();
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
        
    }//GEN-LAST:event_txtHSNKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStocksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStocksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStocksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStocksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStocksFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnViewStock;
    private javax.swing.JComboBox<String> cmbTax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblClick;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPath;
    private javax.swing.JTextField txtHSN;
    private javax.swing.JTextField txtItem;
    private javax.swing.JLabel txtcode;
    // End of variables declaration//GEN-END:variables
}
